[qanda]
Why does the *Flatten* feature cause my displayed spectrum to curve steeply upward near the edges, before falling where the IF filter cuts off?::

_WSJT-X_ does not expect a steep filter edge within the displayed
passband, except perhaps a low-frequency cutoff below 200 Hz. Either
use a wider IF filter or reduce the displayed passband by decreasing
*Bins/Pixel*, increasing *Start*, or reducing the width of the *Wide
Graph*.  You might also choose to re-center the filter passband, if
such control is available.


My rig has only a single SSB filter, about 2700 Hz bandwidth.  Can I use split mode?::

Set the radio to *Split* mode and _Split Operation_ to *Rig* (or if
necessary, *Fake It*) on the *Settings | Radio* tab.  To operate
primarily in the JT9 frequency range, check the *{plus}2 kHz*
box. VFO-A will then be moved up to 14.078 MHz.  The JT9 sub-band now
falls between about 500 Hz and 2000Hz on the waterfall display.  As
described above, VFO-B will be adjusted so as to keep your Tx audio
always between 1500 and 2000 Hz.  To operate JT65, simply uncheck the
*{plus}2 kHz* option.  If your rig has an IF shift control or
equivalent (``passband tuning''), you can operate as if you had 4 kHz
Rx bandwidth and use the IF shift control to focus on any 2.7 kHz
portion of the JT65 and JT9 sub-bands.

How should I configure _WSJT-X_ to run multiple instances?::

Start _WSJT-X_ from a command-prompt window, passing each instance a
unique identifier as in the following two-instance example.  This
procedure will isolate the *Settings* file and the writable file
location for each instance of _WSJT-X_.
+
=====
wsjtx --rig-name=TS2000

wsjtx --rig-name=FT847
=====

When setting up rig control through _OmniRig_, something goes wrong when I click *Test CAT*.  What can I do about it?::

_OmniRig_ apparently has a bug that appears when you click *Test CAT*.
Forget using *Test CAT* and just click *OK*.  _OmniRig_ then behaves
normally.

I am using _WSJT-X_ with _Ham Radio Deluxe_.  All seems well until I start HRD Logbook or DM780 running in parallel; then CAT control becomes unreliable.::

You may see delays up to 20 seconds or so in frequency changes or
other radio commands, due to a bug in HRD.  HRD folks are aware of the
problem, and are working to resolve it.

I am running _WSJT-X_ under Ubuntu 14.04.  The program starts, but menu bar is missing from the top of the main window and the hot-keys don't work.::

The new ``Unity'' desktop puts the menu for the currently active
window at the top of the primary display screen.  You can restore menu
bars to their traditional locations by typing the following in a
command-prompt window:

=====
sudo apt-get remove appmenu-qt5 
=====
