!      include 'wsjt1.f'
      include 'avesp2.f'
      include 'bzap.f'
      include 'spec441.f'
      include 'spec2d.f'
      include 'mtdecode.f'
      include 'stdecode.f'
      include 'indexx.f'
      include 's2shape.f'
      include 'flat2.f'

      include 'gen65.f'
      include 'chkmsg.f'

      include 'gen6m.f'
      include 'gentone.f'
      include 'syncf0.f'
      include 'syncf1.f'
      include 'synct.f'
      include 'decode6m.f'
      include 'avemsg6m.f'
