      include 'set.f'
      include 'flatten.f'
      include 'db.f'
      include 'pctile.f'
      include 'sort.f'
      include 'ssort.f'
      include 'ps.f'
      include 'smooth.f'
      include 'ping.f'
      include 'longx.f'
      include 'peakup.f'
      include 'sync.f'
      include 'detect.f'

      include 'avemsg65.f'
      include 'decode65.f'
      include 'demod64a.f'
      include 'encode65.f'
      include 'extract.f'
      include 'flat1.f'

#ifdef Win32
!      include 'four2a.f'       !Multi-threading problems with FFTW3
      include 'four2.f'
#else
      include 'four2.f'
      include 'rfile2.f'
#endif

      include 'gencw.f'
      include 'getpfx1.f'
      include 'getpfx2.f'
      include 'getsnr.f'
      include 'graycode.f'
      include 'grid2k.f'
      include 'interleave63.f'
      include 'k2grid.f'
      include 'limit.f'
      include 'lpf1.f'
      include 'deep65.f'
      include 'morse.f'
      include 'nchar.f'
      include 'packcall.f'
      include 'packgrid.f'
      include 'packmsg.f'
      include 'packtext.f'
      include 'setup65.f'
      include 'short65.f'
      include 'slope.f'
      include 'spec2d65.f'
      include 'sync65.f'
      include 'unpackcall.f'
      include 'unpackgrid.f'
      include 'unpackmsg.f'
      include 'unpacktext.f'
      include 'xcor.f'
      include 'xfft.f' 
      include 'wsjt65.f'

