# Version number components
set (WSJTX_VERSION_MAJOR 1)
set (WSJTX_VERSION_MINOR 4)
set (WSJTX_VERSION_PATCH 0)
set (WSJTX_RC 2)
set (WSJTX_VERSION_IS_RELEASE 0)

set (CONFIG_TEST_VERSION_MAJOR 0)
set (CONFIG_TEST_VERSION_MINOR 2)
set (CONFIG_TEST_VERSION_PATCH 13)
