#!/bin/sh
if [ -e /usr/local/bin/python ] ; then
	LOCALBASE=/usr/local/
else
	LOCALBASE=/usr/
fi
if [ ! -e ~/.wsjt ] ; then
	mkdir ~/.wsjt
	mkdir ~/.wsjt/RxWav
fi
if [ ! -e ~/.wsjt/CALL3.TXT ] ; then
	cp -f ${LOCALBASE}/share/wsjt/CALL3.TXT ~/.wsjt
fi
cd ~/.wsjt
python ${LOCALBASE}/bin/wsjt.py
