@startuml

interface IProtocol {
    encode()
    decode()
}
interface IDecoder
interface IEncoder
interface IDecode

IDecoder <-- IProtocol
IEncoder <-- IProtocol

class FT8
IProtocol <|-- FT8

@enduml
