// Status=review
=== Standard Exchange
By longstanding tradition, a minimal valid QSO requires the exchange
of callsigns, a signal report or some other information, and
acknowledgments.  _WSJT-X_ is designed to facilitate making such
minimal QSOs using short, formatted messages.  The process works best
if you use these formats and follow standard operating practices.  The
recommended basic QSO goes something like this:

[width="90%",cols="3,7,12",options="header"]
|=======================================
|UTC|Transmitted Message|Comment
|0001|CQ K1ABC FN42|K1ABC calls CQ
|0002|K1ABC G0XYZ IO91|G0XYZ answers
|0003|G0XYZ K1ABC –19|K1ABC sends report
|0004|K1ABC G0XYZ R–22|G0XYZ sends acknowledgment and report
|0005|G0XYZ K1ABC RRR|K1ABC sends acknowledgment
|0006|K1ABC G0XYZ 73|G0XYZ sends 73
|=======================================

*Standard messages* consist of two callsigns (or CQ, QRZ, or DE and
one callsign) followed by the transmitting station’s grid locator, a
signal report, R plus a signal report, or the final acknowledgements
RRR or 73.  These messages are compressed and encoded in a highly
efficient and reliable way, and may contain up to 18 characters in
uncompressed form.

*Signal reports* are specified as signal-to-noise ratio (S/N) in dB,
using a standard reference noise bandwidth of 2500 Hz.  Thus, in
example message #0003, K1ABC is telling G0XYZ that his signal is 19 dB
below the noise power in bandwidth 2500 Hz.  In message #0004, G0XYZ
acknowledges receipt of that report and responds with a –22 dB signal
report.  JT65 reports are constrained to lie in the range –30 to –1
dB, while JT9 supports the extended range –50 to +49 dB.

TIP: Signals become visible on the waterfall around S/N = –26 dB and
audible (to those with very good hearing) around –15 dB. Thresholds
for signal decodability are approximately –24 dB for JT65, –26 dB for
JT9.

*Free Text Messages*: Users often add some friendly chit-chat at the
end of a QSO.  Free-format messages such as ``TNX JOE 73'' or ``5W
VERT 73 GL'' are supported, up to a maximum of 13 characters
(including spaces).  It should be obvious that the JT9 and JT65
protocols are not suitable for extensive conversations or rag-chewing.

=== Compound Callsigns

Compound callsigns such as xx/K1ABC or K1ABC/x are handled in one of
two possible ways.  

.Type 1 Compound-Callsign Messages

A list of about 350 of the most common prefixes and suffixes can be
displayed from the *Help* menu.  A single compound callsign involving
one item from this list can be used in a message in place of the third
``word'' (normally a locator, signal report, RRR, or 73).  Thus, the
following examples are all properly formatted *Type 1* messages:

 CQ ZA/K1ABC
 CQ K1ABC/4
 ZA/K1ABC G0XYZ
 G0XYZ K1ABC/4

However, the following messages are _not_ valid because a third
word is not permitted in a *Type 1* compound callsign message:

 ZA/K1ABC G0XYZ -22        #These messages will be sent
 G0XYZ K1ABC/4 73          #without the third word 

A QSO between two stations using *Type 1* compound-callsign messages
might look like this:

 CQ ZA/K1ABC
                     ZA/K1ABC G0XYZ
 G0XYZ K1ABC –19
                     K1ABC G0XYZ R–22
 G0XYZ K1ABC RRR
                     K1ABC G0XYZ 73

Notice that both operators have sent and received the full compound
callsign in the first two transmissions; after that, they omit the
add-on prefix or suffix.

.Type 2 Compound-Callsign Messages

Prefixes and suffixes _not_ found in the short displayable list can be
handled in a *Type 2* message.  The compound callsign must be the
second word in a two- or three-word message, and the first word must
be CQ, DE, or QRZ.  Prefixes can be up 1-4 characters, suffixes 1-3
characters.  A third word conveying a locator, report, RRR, or 73 is
optional.  The following are valid *Type 2* messages with compound
callsigns:

 CQ W4/G0XYZ FM07          #OK because W4 is not in short-list
 DE W4/G0XYZ -22
 QRZ K1ABC/VE6 DO33        #OK because VE6 is not in short-list

In each case, the message is treated as *Type 2* because the add-on
prefix or suffix is not one of those in the displayable liet.  Note
that a second callsign is never permissible in these messages, but a
locator, report, RRR, or 73 is allowed.

TIP: Remember that your transmitted message is always displayed in the
first panel of the *Status Bar*, highlighted in yellow, exactly as another
station will receive it.

A QSO between two stations using *Type 2* compound-callsign messages
might look like this:

 CQ KP4/K1ABC FK68
                     DE G0XYZ/P IO91
 G0XYZ K1ABC –19
                     K1ABC G0XYZ R–22
 G0XYZ K1ABC RRR
                     DE G0XYZ/P 73

=== Pre-QSO Checklist

Before attempting your first QSO with JT9 or JT65, be sure to go
through the <<X15,Basic Tutorial>> above and the following checklist:

- Your callsign and grid locator set to correct values
- PTT and CAT control (if used) properly configured and tested
- Computer clock properly synchronized to UTC within ±1 s
- Radio set to USB (upper sideband) mode
- Radio's Split mode selected or not, consistent with your choice 
on *Station* tab of the *Setup | Configuration* window.

IMPORTANT: Remember that JT9 and J65 generally do not require high
power. Under most propagation conditions, [red]*QRP is the rule!*
