CC = gcc
CFLAGS = -O2 -Wall -I. -D_WIN32

# Default rules
%.o: %.c
	${CC} ${CFLAGS} -c $<
%.o: %.f
	${FC} ${FFLAGS} -c $<
%.o: %.F
	${FC} ${FFLAGS} -c $<
%.o: %.f90
	${FC} ${FFLAGS} -c $<
%.o: %.F90
	${FC} ${FFLAGS} -c $<

all:	qra65sim.exe

OBJS1 = main.o qra65.o

qra65sim.exe: $(OBJS1) 
	${CC} -o qra65sim.exe $(OBJS1) ../qracodes/libqra65.a -lm

.PHONY : clean

clean:
	$(RM) *.o qra65sim.exe
