[[NEW_FEATURES]]
=== New in Version {VERSION_MAJOR}.{VERSION_MINOR}

- _WSJT-X 2.6_ implements new features supporting the ARRL
International Digital Contest and its distance based scoring.  The
*Call 1st* checkbox has been replaced by a drop-down control offering
*CQ Max Dist* as an alternative.  With this option selected, the
program will select the reply to your CQ that yields the most contest
points.  In addition, a new window labeled *Active Stations* displays
a list of received but unworked callsigns, sorted in decreasing order
of potential contest points.  Click on a line in this window to call
that station.

- Decoding performance for FT8 and Q65 has been improved in a variety
of situations with available _a priori_ (AP) information.

- *Echo* mode now offers a *Clear Avg* button and produces reliable
measurements of SNR even when Doppler spread is large.  The *Measure*
function can be used to measure SNR for a received unmodulated carrier
-- for example, a key-down test signal emitted by another station and
reflected from the Moon.

- New buttons on the main window allow quick changes between modes
FT4, FT8, MSK144, Q65, and JT65.  Another new button allows toggling
FT8 Hound mode ON or OFF.

- Optional color highlighting is provided for specified DX Call and DX
Grid, and for messages containing RR73 or 73.

- New options are provided for writing to file ALL.TXT.  You can
request automatic starting of a new file every month or every year,
and you can disable writing altogether.

- Other changes include bug fixes and rig control for some new radios.

- _MAP65 3.0_ (available for Windows only) now sends additional
information to file azel.dat and offers digital scaling of input I/Q
data.

