=== New in Version {VERSION}

The most important feature added to _WSJT-X_ since Version 2.0.1 is
the new *FT4 protocol*, designed especially for radio contesting.  It
has T/R sequence length 7.5 s, bandwidth 80 Hz, and threshold
sensitivity -17.5 dB.  Version 2.1.0 also has improvements to FT8
waveform generation, contest logging, rig control, the user interface,
and accessibility, as well as a number of bug fixes.

=== Documentation Conventions

In this manual the following icons call attention to particular types
of information:

NOTE: *Notes* containing information that may be of interest to
particuar classes of users.

TIP: *Tips* on program features or capabilities that might otherwise be
overlooked.

IMPORTANT: *Warnings* about usage that could lead to undesired
consequences.

=== How You Can Contribute

_WSJT-X_ is part of an open-source project released under the
{gnu_gpl} (GPLv3). If you have programming or documentation skills or
would like to contribute to the project in other ways, please make
your interests known to the development team.  The project's
source-code repository can be found at {devrepo}, and communication
among the developers takes place on the email reflector {devmail}.
Bug reports and suggestions for new features, improvements to the
_WSJT-X_ User Guide, etc., may also be sent to the {wsjt_yahoo_group}
email reflector.  You must join the relevant group before posting to
either email list.
