=== New in Version 1.8

For quick reference, here's a short list of features and capabilities
added to _WSJT-X_ since Version 1.7.0:

- New mode *FT8* designed for fast QSOs

- New tool *FreqCal* for accurate frequency calibration of your radio

- Improved decoding performance for JT65, QRA64, and MSK144

- *SWL* option for third-party decoding short-format MSK144 messages

- Experimental amplitude and phase equalization for MSK144
    
- Options to minimize screen space used by *Main* and *Wide Graph*
windows
    
- New set of suggested default frequencies specific to the three IARU
regions

- Enhanced scheme for managing table of suggested default operating
frequencies

- Improved CAT control for many radios, including those controlled
through Commander or OmniRig

- Bug fixes and minor tweaks to user interface

=== Documentation Conventions

In this manual the following icons call attention to particular types
of information:

NOTE: *Notes* containing information that may be of interest to
particuar classes of users.

TIP: *Tips* on program features or capabilities that might otherwise be
overlooked.

IMPORTANT: *Warnings* about usage that could lead to undesired
consequences.

=== How You Can Contribute

_WSJT-X_ is part of an open-source project released under the
{gnu_gpl} (GPL). If you have programming or documentation skills or
would like to contribute to the project in other ways, please make
your interests known to the development team.  The project's
source-code repository can be found at {devsvn}, and most
communication among the developers takes place on the email reflector
{devmail}.  Bug reports and suggestions for new features, improvements
to the _WSJT-X_ User Guide, etc., may also be sent to the
{wsjt_yahoo_group} email reflector.  You must join the relevant group
before posting to either email list.
