[[NEW_FEATURES]]
=== New in Version {VERSION_MAJOR}.{VERSION_MINOR}

_WSJT-X 2.5_ introduces an enhanced Q65 decoder that measures and
compensates for linear frequency drifts of Q65 signals.  Activate this
feature by setting a spinner control *Max Drift* on the _WSJT-X_ main
window to a number greater than 0.  We suggest a setting of 10 for
submode Q65-60A, the recommended submode for EME on 50 and 144 MHz,
which will accommodate drift rates up to 20 Hz/minute.  Similarly, we
suggest *Max Drift* = 40 for submode Q65-15C, used for for 10 GHz QSOs
(up to 900 km) via aircraft scatter and drift rates up to about 20
Hz/s. When *Max Drift* = 50 the decoder will use an enhanced algorithm
to compensate for larger aircraft scatter drift rates, successful
decodes with this algorithm are tagged with a `q5` indicator.

On the Windows platform only, _WSJT-X 2.5_ installations now include
an early version of _MAP65 3.0_.  This program works together with
suitable hardware that converts RF to baseband.  The hardware/software
combination implements a wideband, highly optimized receiver for the
Q65 and JT65 protocols, with matching transmitting features that
require a standard SSB transceiver.  _MAP65_ is effective in both
single-polarization and dual-polarization systems.  If two
polarization channels are available, _MAP65_ determines and matches
the linear polarization angle of each decodable signal.  This
capability provides a major advantage for efficient EME communication
on bands up to 432 MHz.  A single-channel _MAP65_ system works
extremely well for EME on 1296 MHz and higher bands, displaying all
signals in a 90 kHz sub-band and decoding all the Q65 and JT65
signals.
