=== New in Version 1.7

For quick reference, here's a short list of features and capabilities
added to _WSJT-X_ since Version 1.6.0:

- New modes: ISCAT, MSK144, QRA64

- Newly implemented submodes: JT65B-C, JT9B-H

- Fast submodes of JT9E-H

- New Franke-Taylor decoder to replace the Koetter-Vardy decoder
previously used for JT65. Separate program `kvasd[.exe]` is no longer
used.

- Improvements to the JT4, JT9, and JT65 decoders

- Multi-pass decoding for JT65 and WSPR.  Decoded signals are
subtracted from the received data, allowing decoding of weaker
signals that were otherwise masked.

- Improved convenience features for EME Doppler tracking

- Saving and restoring of multiple program configurations

- Sample-file download facility

- Many corrections and improvements to the Hamlib library, fixing
balky rig-control features

- Power settings for Transmit and Tune remembered and optionally
restored for each band

=== Documentation Conventions

In this manual the following icons call attention to particular types
of information:

NOTE: Tidbits of information that may be of interest to particuar
classes of users.

TIP: Helpful advice on program features or capabilities that might
otherwise be overlooked.

IMPORTANT: Warnings about usage that could lead to undesired
consequences.

=== How You Can Contribute

_WSJT-X_ is part of an open-source project released under the
{gnu_gpl} (GPL). If you have programming or documentation skills or
would like to contribute to the project in other ways, please make
your interests known to the development team.  The project's
source-code repository can be found at {devsvn}, and most
communication among the developers takes place on the email reflector
{devmail}.  Bug reports and suggestions for new features, improvements
to the _WSJT-X_ User Guide, etc., may also be sent to the
{wsjt_yahoo_group} email reflector.
