=== New in Version 1.9

For quick reference, here's a short list of features and capabilities
added to _WSJT-X_ since Version 1.8.0:

- New *FT8 DXpedition Mode* to facilitate high-rate QSOs in a pileup

- "A priori" (AP) decoding and other decoding improvements for JT65 mode

- Improved decoding performance for WSPR, especially effective at LF and MF

- Minor adjustments to auto-sequencing behavior

- Improved Doppler control features for EME

- Improved waterfall sensitivity for very weak signals

- Automatic real-time forwarding of logged information to N1MM Logger+

- Expanded and improved UDP messages for companion programs

- Bug fixes and minor tweaks to user interface

=== Documentation Conventions

In this manual the following icons call attention to particular types
of information:

NOTE: *Notes* containing information that may be of interest to
particuar classes of users.

TIP: *Tips* on program features or capabilities that might otherwise be
overlooked.

IMPORTANT: *Warnings* about usage that could lead to undesired
consequences.

=== How You Can Contribute

_WSJT-X_ is part of an open-source project released under the
{gnu_gpl} (GPL). If you have programming or documentation skills or
would like to contribute to the project in other ways, please make
your interests known to the development team.  The project's
source-code repository can be found at {devsvn}, and most
communication among the developers takes place on the email reflector
{devmail}.  Bug reports and suggestions for new features, improvements
to the _WSJT-X_ User Guide, etc., may also be sent to the
{wsjt_yahoo_group} email reflector.  You must join the relevant group
before posting to either email list.
