[[NEW_FEATURES]]
=== New in Version {VERSION_MAJOR}.{VERSION_MINOR}

_WSJT-X 2.6_ implements features in support of the ARRL International
Digital Contest.  This contest's scoring is distance based, so the
*Call 1st* checkbox is replaced by a drop-down control offering *CQ
Max Dist* as an alternative.  A new window labeled *Active Stations*
displays a list of received but unworked callsigns sorted in
decreasing order of potential contest points.  See Section 7.4 for
more details on these features.

Decoding performance for FT8 and Q65 has been improved for situations
where _a priori_ (AP) information is available.

*Echo* mode now offers a button labeled *Clear Avg* and produces
reliable measurements of SNR and Doppler spread.  The related
*Measure* function can be used to measure these quantities for a
received unmodulated carrier -- for example, a key-down test signal
emitted by another station and reflected from the Moon.

New buttons on the main window allow quick changes between the modes
FT4, FT8, MSK144, Q65, and JT65.  Another button allows toggling the
FT8 Hound mode ON or OFF.

Optional highlighting is provided for DX Call and DX Grid, and for
messages containing RR73 or 73.

New options are provided for writing to file ALL.TXT.  You can request
starting a suitably labeled new file every month or every year, and you
can disable writing altogether.

