=== Decoded Lines

Displayed information accompanying decoded messages generally includes UTC,
signal-to-noise ratio in dB, time offset DT in seconds, and
audio frequency in Hz.  Some modes include additional information such
as frequency offset from nominal (DF), frequency drift (Drift or F1),
or distance (km or mi).

There may also be some cryptic characters with special meanings
summarized in the following Table:

[[DECODED_LINES_TABLE]]
.Notations used on decoded text lines
[width="50%",cols="h,3*^",frame=topbot,options="header"]
|===========================================
|Mode    |Mode character|Sync character|End of line information
|JT4     | $            | *, # | f, fN, dNC
|JT9     | @            |      |
|JT65    | #            |      |
|JT65 VHF| #            | *, # | f, fN, dNC
|QRA64   | :            | *    | R
|ISCAT   |              | *    | M  N  C  T
|MSK144  | &            |      | N
|===========================================
Sync character::
 `*` - Normal sync +
 `#` - Alternate sync

End of line information::
 `C` - Confidence indicator [ISCAT and Deep Search; (0-9,*)] +
 `d` - Deep Search algorithm +
 `f` - Franke-Taylor or Fano algorithm +
 `M` - Message length (characters) +
 `N` - Number of Rx intervals or frames averaged +
 `R` - QRA64 _a priori_ return code +
 `T` - Length of analyzed region (s)

=== Reference Spectrum

WSJT-X provides a tool that can be used to determine the detailed
shape of your receiver's passband.  Disconnect your antenna or tune to
a quiet frequency with no signals.  With WSJT-X running in one of the
slow modes, select *Measure reference spectrum* from the *File* menu.
Wait for about a minute and then hit the *Stop* button.  A file named
`refspec.dat` should appear in your log directory.  

 [ ... more to come ...]
