=== Decoded Lines

Displayed information accompanying decoded messages generally includes UTC,
signal-to-noise ratio in dB, time offset DT in seconds, and
audio frequency in Hz.  Some modes include additional information such
as frequency offset from nominal (DF), frequency drift (Drift or F1),
or distance (km or mi).

There may also be some cryptic characters with special meanings
summarized in the following Table:

[[DECODED_LINES_TABLE]]
.Notations used on decoded text lines
[width="50%",cols="h,3*^",frame=topbot,options="header"]
|===========================================
|Mode    |Mode character|Sync character|End of line information
|FT8     | ~            |      | aP
|JT4     | $            | *, # | f, fN, dNC
|JT9     | @            |      |
|JT65    | #            |      |
|JT65 VHF| #            | *, # | f, fN, dNC
|QRA64   | :            | *    | R
|ISCAT   |              | *    | M  N  C  T
|MSK144  | &            |      | N
|===========================================
Sync character::
 `*` - Normal sync +
 `#` - Alternate sync

End of line information::
 `a` - Decoded with aid of some a priori (AP) information
 `C` - Confidence indicator [ISCAT and Deep Search; (0-9,*)] +
 `d` - Deep Search algorithm +
 `f` - Franke-Taylor or Fano algorithm +
 `M` - Message length (characters) +
 `N` - Number of Rx intervals or frames averaged +
 `P` - Number indicating type of AP information (see table below)
 `R` - Return code from QRA64 decoder +
 `T` - Length of analyzed region (s)

[[AP_INFO_TABLE]]
.AP information types
[width="25%",cols="h10,<m20",frame=topbot,options="header"]
|===========================================
|P | Message components
|1 | CQ   &#160; &#160;   ?   &#160; &#160;   ? 
|2 | DE   &#160; &#160;   ?   &#160; &#160;   ? 
|3 | MyCall &#160; &#160; ?   &#160; &#160;   ? 
|4 | MyCall DxCall &#160; &#160;  ? 
|5 | MyCall DxCall RRR
|6 | MyCall DxCall 73
|7 | MyCall DxCall RR73
|8 |   ? &#160; &#160;   DxCall &#160; &#160; ?
|===========================================


=== Reference Spectrum

WSJT-X provides a tool that can be used to determine the detailed
shape of your receiver's passband.  Disconnect your antenna or tune to
a quiet frequency with no signals.  With WSJT-X running in one of the
slow modes, select *Measure reference spectrum* from the *File* menu.
Wait for about a minute and then hit the *Stop* button.  A file named
`refspec.dat` should appear in your log directory.  

 [ ... more to come ...]
